server:
  port: 8081

spring:
  application:
    name: 永雏塔菲
  mail:
    host: smtp.yeah.net
    username: ENC(hwCnHhD0xEbH8rokoiMFgaFESy31EYKr6E+Dcp2/75s=)
    password: ENC(IbeI2jNuBY+bxDgucULNTWL0AECF2btV+bKPcL4xWhA=)
    from: ENC(Hcz9lzwHj/SbuNURxsMaimXAuor5DHoB8t3Q8HdJ/xdKN8CqU4OhMg==)
  datasource:
    url: ENC(5EL8W5f7mmuBc8vej1LQDkh8PdLL1Am/QaiRMGq3oPeLZKuBTzX8MiM6rmTuY2+Sg8kJNkMzm9oTTuNv5uakGtdA5De+pXdHIRGr1aFQwy/VztmfMcBbl0RL33cg6kH8)
    username: root
    password: ENC(vxS8qF46MFx74tDPiBCbthRpU/AbrOcw)
    driver-class-name: com.mysql.cj.jdbc.Driver
  #redis
  redis:
    host: ENC(vFPwbiT1vGfQ/h4IRYltiKxr3g6J64xb)
    password: ENC(LyjiFW+Qfm1VdPUyyRWJjePElB5HN+XN)

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml
#接口文档
knife4j:
  enable: true

# 加密算法
jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator