server:
  port: 8081

spring:
  mail:
    host: smtp.yeah.net
    username: 111
    password: 1111
    from: Vanilla<111>
  datasource:
    url: jdbc:mysql://localhost:3306/sg_security?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: dyh20030815
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/**/*.xml

knife4j:
  enable: true
  openapi:
    title: 测试文档
    description: 111